### ISSUE TITLE
Help on picoscope module installation and use (list of commands)

### ISSUE THREAD

**Issue by eldarintar** [colinoflynn/pico-python#165]
Hello,

I  am trying to use python to access my Picoscope 3205D device, but after installing the module, I can’t find any description on how to use it, i.e. a list of all commands and their effects.

Does someone have a documentation on these commands ?

**Comment by colinoflynn** [comment]
The documentation is really in the source files - it's all Python API, not so much "commands". These just implement the picoscope API, you can see the picoscope documentation for those.

Note this isn't the official picoscope interface either, you may get better support from their forum for more general questions.

**Comment by eldarintar** [comment]
I found [this documentation](https://www.picotech.com/download/manuals/picoscope-3000-series-a-api-programmers-guide.pdf) but it doesn’t help with programming in python.
I looked at the examples of the package but none is working, I keep having diverse error messages… The kind of documentation I am looking for is the one that could e.g. help me write such programs : the name on the modules to lobd, how to connect to a device, to set thing and get the data back.

**Comment by eldarintar** [comment]
To be a bit more specific, after having installed "picoscope" with pip, I open "test_ps3000a.py" with IDLE, run it, and here is what I get :

Traceback (most recent call last):
  File "C:\Users\Julien Wengler\Desktop\python\picoscope-0.7.11\picoscope-0.7.11\examples\test_ps3000a.py", line 8, in <module>
    ps = ps3000a.PS3000a(SERIAL_NUM)
  File "C:\Python27\lib\site-packages\picoscope\ps3000a.py", line 149, in __init__
    super(PS3000a, self).__init__(serialNumber, connect)
  File "C:\Python27\lib\site-packages\picoscope\picobase.py", line 147, in __init__
    self.open(serialNumber)
  File "C:\Python27\lib\site-packages\picoscope\picobase.py", line 857, in open
    self._lowLevelOpenUnit(serialNumber)
  File "C:\Python27\lib\site-packages\picoscope\ps3000a.py", line 171, in _lowLevelOpenUnit
    self.checkResult(m)
  File "C:\Python27\lib\site-packages\picoscope\picobase.py", line 900, in checkResult
    str(inspect.stack()[1][3]), ecName, ecDesc))
IOError: Error calling _lowLevelOpenUnit: PICO_NOT_FOUND (No PicoScope XXXX could be found.)

**Comment by hmaarrfk** [comment]
You may wish to start studying:
https://github.com/colinoflynn/pico-python/blob/master/picoscope/ps3000.py

the `picoscope.py` file, calls these little wrappers on the C functions to make the code feel more like python.

We don't know how the picoscopes work internally, so we purposefully avoided writing an kind of documentation.

We feel that the manual you found, along with the python source code we wrote, should be enough to get going.

As always, there are installation issues. We encourage you to search through the issues on github where many users may have already faced similar ones.
