### ISSUE TITLE
ps6000.py _lowLevelGetTimebase returns error 14 for timebase 0 (200 ps) for PS6404C

### ISSUE THREAD

**Issue by otamichalekSTFC** [colinoflynn/pico-python#182]
Hi, I am trying to use timebase 0 as in [Programmer's guide](https://www.picotech.com/download/manuals/picoscope-6000-series-programmers-guide.pdf)/2.7 Timebases. I am currently only able to achieve timebase 2 (800 ps between points), but for 1 and 0, the device returns an error 14.

The error comes from the ps6000.py _lowLevelGetTimebase  method: m = self.lib.ps6000GetTimebase2 ... on line 298 of ps6000.py. I tried the following to see if I might not be using too many or not enough samples (timebase only works when > 2):
```
    peaksmax = 100
    samples = int(((12.5E-9)*peaksmax)/(2E-10))
    timebase =0

    for i in range(0,samples):
        m = ps.lib.ps6000GetTimebase2(c_int16(ps.handle), c_uint32(timebase),
                                            c_uint32(i), byref(c_float()),
                                            c_int16(0), byref(c_int32()),
                                            c_uint32(0))
        print("{} samples, error: {}".format(i,m))
        if m == 0:
            break
```

I kept getting m = 14, which stops the script from claiming an incorrect time base.

```Traceback (most recent call last):
  File "ps6000_demo.py", line 83, in <module>
    ps.setSamplingInterval(sampling_interval, obs_duration)
  File "/home/user/.local/lib/python3.7/site-packages/picoscope/picobase.py", line 376, in setSamplingInterval
    self.timebase, noSamples, oversample, segmentIndex)
  File "/home/user/.local/lib/python3.7/site-packages/picoscope/ps6000.py", line 302, in _lowLevelGetTimebase
    self.checkResult(m)
  File "/home/user/.local/lib/python3.7/site-packages/picoscope/picobase.py", line 1150, in checkResult
    str(inspect.stack()[1][3]), ecName, ecDesc))
OSError: Error calling _lowLevelGetTimebase: PICO_INVALID_TIMEBASE (The timebase is not supported or is invalid.)
```

Could you please help? Maybe I'm doing something wrong or it also might be the c wrapper issue?

**Comment by hmaarrfk** [comment]
Please provide full code needed to reproduce the issue. Some notes in the guide state that the maximum time base depends on the number of enabled channels.

**Comment by otamichalekSTFC** [comment]
Hi, here you go.

```
from __future__ import division
from __future__ import absolute_import
from __future__ import print_function
from __future__ import unicode_literals

import time
from picoscope import ps6000
import matplotlib.pyplot as plt
import numpy as np

if __name__ == "__main__":
    #print(__doc__)

    print("Attempting to open Picoscope 6000...")

    ps = ps6000.PS6000()

    print("Found the following picoscope:")
    #print(ps.getAllUnitInfo())

    
    obs_duration = 1E-9 #(12.5E-9)*5
    #sampling = 64
    
    sampling_interval = 0.2E-9

    #sampling_interval = obs_duration / sampling

    """ 
    (actualSamplingInterval, nSamples, maxSamples) = \
        ps.setSamplingInterval(sampling_interval, obs_duration)

    """  
    
    
    peaksmax = 100
    samples = int(((12.5E-9)*peaksmax)/(2E-10))
    timebase =0

    for i in range(0,samples):
        m = ps.lib.ps6000GetTimebase2(c_int16(ps.handle), c_uint32(timebase),
                                            c_uint32(i), byref(c_float()),
                                            c_int16(0), byref(c_int32()),
                                            c_uint32(0))
        print("{} samples, error: {}".format(i,m))
        if m == 0:
            break

    (actualSamplingInterval, nSamples, maxSamples) = \
        ps.setSamplingInterval(sampling_interval, obs_duration)
    
    print("Sampling interval = {:.3f} ns".format(actualSamplingInterval * 1E9))
    print("Taking  samples = %d" % nSamples)
    print("Maximum samples = %d" % maxSamples)

    channelRange = ps.setChannel('A', 'DC', 0.05, 0.0, enabled=True,
                                 BWLimited=False)
    print("Chosen channel range = {:.3f}".format(channelRange))

    ps.setSimpleTrigger('A', 0.025, 'Rising', timeout_ms=1, enabled=True)


    time.sleep(2.0)
    ps.runBlock()
    ps.waitReady()
    print("Done waiting for trigger")
    
    dataA = ps.getDataV('A', nSamples, returnOverflow=False)
    dataTimeAxis = np.arange(nSamples) * actualSamplingInterval * 1E9

    ps.stop()
    ps.close()

    plt.plot(dataTimeAxis, dataA,"-o")
    plt.grid(True, which='major')
    plt.title("Picoscope 6000 waveforms")
    plt.ylabel("Voltage (V)")
    plt.xlabel("Time (ns)")
    plt.show()
```

Many thanks!

**Comment by hmaarrfk** [comment]
where is line 83 in the provided example....

**Comment by otamichalekSTFC** [comment]
Excuse me? It's 79 lines total?

**Comment by hmaarrfk** [comment]
![image](https://user-images.githubusercontent.com/90008/168554303-6c6a5b96-facf-4f9d-9aa9-04ebc2ab1239.png)

you showed an error from line 83, 

im trying to help debug with the provided information but it is inconsistent,

please provide self consistent information.

**Comment by otamichalekSTFC** [comment]
Oh I see. Sorry. The for loop was for testing. This is the initial code which returned the error. In this code the line 83 from error message is on line 25 as I removed the docs (I edited the example for ps5000).

```
from __future__ import division
from __future__ import absolute_import
from __future__ import print_function
from __future__ import unicode_literals

import time
from picoscope import ps6000
import matplotlib.pyplot as plt
import numpy as np

if __name__ == "__main__":
    #print(__doc__)

    print("Attempting to open Picoscope 6000...")

    ps = ps6000.PS6000()

    print("Found the following picoscope:")
    #print(ps.getAllUnitInfo())

    
    obs_duration = (12.5E-9)*5    
    sampling_interval = 0.2E-9

    (actualSamplingInterval, nSamples, maxSamples) = ps.setSamplingInterval(sampling_interval, obs_duration)
    
    print("Sampling interval = {:.3f} ns".format(actualSamplingInterval * 1E9))
    print("Taking  samples = %d" % nSamples)
    print("Maximum samples = %d" % maxSamples)

    channelRange = ps.setChannel('A', 'DC', 0.05, 0.0, enabled=True,
                                 BWLimited=False)
    print("Chosen channel range = {:.3f}".format(channelRange))

    ps.setSimpleTrigger('A', 0.025, 'Rising', timeout_ms=1, enabled=True)


    time.sleep(2.0)
    ps.runBlock()
    ps.waitReady()
    print("Done waiting for trigger")
    
    dataA = ps.getDataV('A', nSamples, returnOverflow=False)
    dataTimeAxis = np.arange(nSamples) * actualSamplingInterval * 1E9

    ps.stop()
    ps.close()

    plt.plot(dataTimeAxis, dataA,"-o")
    plt.grid(True, which='major')
    plt.title("Picoscope 6000 waveforms")
    plt.ylabel("Voltage (V)")
    plt.xlabel("Time (ns)")
    plt.show()
```

**Comment by hmaarrfk** [comment]
I'm going to ask one more thing:

Can you remove all lines of code after the error.
Then remove all lines of code before the error that are unrelated to the error.

This helps us really focus.

**Comment by otamichalekSTFC** [comment]
Ok. Hopefully, this is ok.

Used python script:
```
from __future__ import division
from __future__ import absolute_import
from __future__ import print_function
from __future__ import unicode_literals

from picoscope import ps6000

ps = ps6000.PS6000()

obs_duration = (12.5E-9)*5    
sampling_interval = 0.2E-9

(actualSamplingInterval, nSamples, maxSamples) = ps.setSamplingInterval(sampling_interval, obs_duration)
```

Returned Error:
```
Traceback (most recent call last):
  File "simple.py", line 13, in <module>
    (actualSamplingInterval, nSamples, maxSamples) = ps.setSamplingInterval(sampling_interval, obs_duration)
  File "/home/clfartpi/.local/lib/python3.7/site-packages/picoscope/picobase.py", line 376, in setSamplingInterval
    self.timebase, noSamples, oversample, segmentIndex)
  File "/home/clfartpi/.local/lib/python3.7/site-packages/picoscope/ps6000.py", line 302, in _lowLevelGetTimebase
    self.checkResult(m)
  File "/home/clfartpi/.local/lib/python3.7/site-packages/picoscope/picobase.py", line 1150, in checkResult
    str(inspect.stack()[1][3]), ecName, ecDesc))
OSError: Error calling _lowLevelGetTimebase: PICO_INVALID_TIMEBASE (The timebase is not supported or is invalid.)
```

**Comment by hmaarrfk** [comment]
Yes much better! Great minimum reproducing example. It really helps us focus.

Honestly, I wonder if any of the "special" timebases work:
![image](https://user-images.githubusercontent.com/90008/168588541-d6e577dd-cf29-41cd-a6df-797172eb4685.png)


I dont have a picoscope, so I can't actually try it. It is likely the fact that we don't compute any of those correctly.

Can you edit: `/home/user/.local/lib/python3.7/site-packages/picoscope/picobase.py` to print out the values of all the parameters that are passed?

**Comment by hmaarrfk** [comment]
so timebase is being correctly provided a value of 0. You might need to disable cannels to get that "fastest" timebase. I know that their scope shares the bandwidth between probes. So you can run all 4 at a sampling rate of 800 pss, or 1 of them at a sampling rate of 200 ps

**Comment by otamichalekSTFC** [comment]
Yes. So you want me to add before the `ps.SetSamplingInterval` something like this?

```
ps.setChannel(channel='A',enabled=True)
ps.setChannel(channel='B',enabled=False)
ps.setChannel(channel='C',enabled=False)
ps.setChannel(channel='D',enabled=False)
```

**Comment by otamichalekSTFC** [comment]
Yeah, that does not return the error value (i.e. `m = 0`, so no error)! Thank you!

I will test it with an oscillator running as it is off now and let you know it works as a whole (which it now seems to).

**Comment by otamichalekSTFC** [comment]
Ok, that works! The other channels need to be disabled prior to going to timebase below 2. Thank you so much!!!

**Comment by hmaarrfk** [comment]
Happy it works. Honestly, their useguide is well written. I would give it a full pass one day:

![image](https://user-images.githubusercontent.com/90008/168596735-9e2544f6-1e96-4546-be92-abdb5f7cf230.png)
