### ISSUE TITLE
AttributeError: 'PS2000a' object has no attribute 'handle'

### ISSUE THREAD

**Issue by wittrup** [colinoflynn/pico-python#84]
I am not able to start using pico-python.
Running this code:
```
from picoscope import ps2000a


print("Attempting to open Picoscope 2000...")
ps = ps2000a.PS2000a()
```

Throws the following errors:
```
C:\Users\wittrup\AppData\Local\Continuum\Anaconda3\python.exe C:/Users/wittrup/Documents/GitHub/pico-python/picoscope/fiddla.py
Attempting to open Picoscope 2000...
Traceback (most recent call last):
  File "C:/Users/wittrup/Documents/GitHub/pico-python/picoscope/fiddla.py", line 5, in <module>
    ps = ps2000a.PS2000a()
  File "C:\Users\wittrup\AppData\Local\Continuum\Anaconda3\lib\site-packages\picoscope\ps2000a.py", line 147, in __init__
    self.lib = windll.LoadLibrary(self.LIBNAME + ".dll")
  File "C:\Users\wittrup\AppData\Local\Continuum\Anaconda3\lib\ctypes\__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\wittrup\AppData\Local\Continuum\Anaconda3\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application
Exception ignored in: <bound method _PicoscopeBase.__del__ of <picoscope.ps2000a.PS2000a object at 0x000001F90198E748>>
Traceback (most recent call last):
  File "C:\Users\wittrup\AppData\Local\Continuum\Anaconda3\lib\site-packages\picoscope\picobase.py", line 825, in __del__
    self.close()
  File "C:\Users\wittrup\AppData\Local\Continuum\Anaconda3\lib\site-packages\picoscope\picobase.py", line 816, in close
    if not self.handle is None:
AttributeError: 'PS2000a' object has no attribute 'handle'
```

Versions:
```
C:\Users\wittrup>ver

Microsoft Windows [Version 10.0.15063]

C:\Users\wittrup>python
Python 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

PicoScope® 6 - PC Oscilloscope software version: 6.12.9.2917
Copyright © 1995-2017, Pico Technology Ltd.

Model: PicoScope 2204A
```

How may I overcome this issue?

**Comment by hmaarrfk** [comment]
Might you have installed the 32 bit libraries instead of the 64 bit ones?

the line
```
OSError: [WinError 193] %1 is not a valid Win32 application
```
indicates that there is a library mismatch. Your python install is 64 bit. You should probably install the 64 bit picoscope libraries

**Comment by IonutGorgos** [comment]
Hello @wittrup,
I have Python 3.6.2 on Win10 x64 machine, but I don't have that problem.
But I installed Python 2.7.13 and I run the same issue like you. All I had to do was change the line 147 in your case to:
`self.lib = windll.LoadLibrary(str(self.LIBNAME + ".dll"))`

**Comment by hmaarrfk** [comment]
Hmm, ok, also I noticed that pip is quite a bit behind the master version of this branch.

I thought it fetched it automatically. There are a few issues with types that have been fixed in recent versions for the ps2000a. Can you try following the instructions to install the package from the git repo instead of pip. I don't have a linux computer at  the moment and git isn't installed on my new computer yet :S.

**Comment by hmaarrfk** [comment]
I think this is the same issue as Issue #91.

Closing it as OP @wittrup  seems to have found a solution.
