### ISSUE TITLE
Macos : IOError: Error calling _lowLevelOpenUnit: None (None)

### ISSUE THREAD

**Issue by sebma** [colinoflynn/pico-python#87]
Hi,

I now have the Picoscope 2208A at hand :)

When I run the `ps2000_demo.py` script on Macos, here is what I get : 

```
Attempting to open Picoscope 2000...
Found the following picoscope:
Traceback (most recent call last):
  File "ps2000_demo.py", line 55, in <module>
    print(ps.getAllUnitInfo())
  File "/Users/mansfeld/src/pico-python/picoscope/picobase.py", line 156, in getAllUnitInfo
    s += key.ljust(30) + ": " + self.getUnitInfo(key) + "\n"
  File "/Users/mansfeld/src/pico-python/picoscope/picobase.py", line 140, in getUnitInfo
    return self._lowLevelGetUnitInfo(info)
  File "/Users/mansfeld/src/pico-python/picoscope/ps2000.py", line 171, in _lowLevelGetUnitInfo
    self.checkResult(m)
  File "/Users/mansfeld/src/pico-python/picoscope/ps2000.py", line 330, in checkResult
    raise IOError('Error calling %s' % (inspect.stack()[1][3]))
IOError: Error calling _lowLevelGetUnitInfo
Exception IOError: IOError(u'Error calling _lowLevelCloseUnit',) in <bound method PS2000.__del__ of <picoscope.ps2000.PS2000 object at 0x10710a8d0>> ignored
```

BTW : On Macos, to `generate a link to your git directory`, you must type : 
`$ sudo python2 setup.py develop`
where python2 is the Python installed by the `brew` utility (`brew install python`)

Can you help me ?

**Comment by hmaarrfk** [comment]
Are you able to try some of their C sample code?

I've never used Mac, so I'm unsure what is going on.

**Comment by sebma** [comment]
@hmaarrfk Hi, I think maybe you can contact PicoTech support for help ?

**Comment by IonutGorgos** [comment]
Hi @sebma,

Open a python cli and enter the following code:
`from picoscope import ps2000
ps=ps2000.PS2000()
`
It is working ?

**Comment by sebma** [comment]
@IonutGorgos  I use a 2208A picoscope, so I added the 'A' at the end of your python instructions : 

When the Picoscope is connected to the Macos : 
```
$ /usr/local/bin/python2
Python 2.7.13 (default, Jul 18 2017, 09:17:00)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from picoscope import ps2000a
>>> ps=ps2000a.PS2000a()
>>> print(ps.getAllUnitInfo())
DriverVersion                 : PS2000A MacOSX Driver, 1.1.6.18
USBVersion                    : 2.0
HardwareVersion               : 1
VariantInfo                   : 2208A
BatchAndSerial                : CY406/005
CalDate                       : 21Mar14
KernelVersion                 : 0.0
DigitalHardwareVersion        : 1
AnalogueHardwareVersion       : 1
PicoFirmwareVersion1          : 1.3.3.0
PicoFirmwareVersion2          : 0.5.47.0
>>> ps.close()
```
When the Picoscope is NOT connected to the Macos : 
```
$ /usr/local/bin/python2
Python 2.7.13 (default, Jul 18 2017, 09:17:00)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from picoscope import ps2000a
>>> ps=ps2000a.PS2000a()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mansfeld/src/pico-python/picoscope/ps2000a.py", line 154, in __init__
    super(PS2000a, self).__init__(serialNumber, connect)
  File "/Users/mansfeld/src/pico-python/picoscope/picobase.py", line 134, in __init__
    self.open(serialNumber)
  File "/Users/mansfeld/src/pico-python/picoscope/picobase.py", line 798, in open
    self._lowLevelOpenUnit(serialNumber)
  File "/Users/mansfeld/src/pico-python/picoscope/ps2000a.py", line 164, in _lowLevelOpenUnit
    self.checkResult(m)
  File "/Users/mansfeld/src/pico-python/picoscope/picobase.py", line 840, in checkResult
    raise IOError('Error calling %s: %s (%s)' % (str(inspect.stack()[1][3]), ecName, ecDesc))
IOError: Error calling _lowLevelOpenUnit: PICO_NOT_FOUND (No PicoScope XXXX could be found.)
>>>
```
If I run the ./ps2000_demo.py script : 
When NOT connected (it works as expected) : 
```
Attempting to open Picoscope 2000...
Traceback (most recent call last):
  File "./ps2000_demo.py", line 52, in <module>
    ps = ps2000a.PS2000a()  # Uncomment this line to use with the 2000a/2000b series
  File "/Users/mansfeld/src/pico-python/picoscope/ps2000a.py", line 154, in __init__
    super(PS2000a, self).__init__(serialNumber, connect)
  File "/Users/mansfeld/src/pico-python/picoscope/picobase.py", line 134, in __init__
    self.open(serialNumber)
  File "/Users/mansfeld/src/pico-python/picoscope/picobase.py", line 798, in open
    self._lowLevelOpenUnit(serialNumber)
  File "/Users/mansfeld/src/pico-python/picoscope/ps2000a.py", line 164, in _lowLevelOpenUnit
    self.checkResult(m)
  File "/Users/mansfeld/src/pico-python/picoscope/picobase.py", line 840, in checkResult
    raise IOError('Error calling %s: %s (%s)' % (str(inspect.stack()[1][3]), ecName, ecDesc))
IOError: Error calling _lowLevelOpenUnit: PICO_NOT_FOUND (No PicoScope XXXX could be found.)
```

My guess is that the shebang I put in the script was wrong : 
`#!/usr/bin/env python2`
This works better : 
`#!/usr/local/bin/python2`

**Comment by sebma** [comment]
@IonutGorgos I think you can close this issue
