### ISSUE TITLE
TypeError: list indices must be integers, not tuple in picobase.py", line 978, in _PicoscopeBase

### ISSUE THREAD

**Issue by sebma** [colinoflynn/pico-python#97]
Hi,

I have the 0.6.1 release of your module and when do a : 
`from picoscope import ps2000a`
I get : 
```
Traceback (most recent call last):
  File "./seb_Acquire.py", line 31, in <module>
    from picoscope import ps2000a # En attandant la resolution du bug#97 https://github.com/colinoflynn/pico-python/issues/97
  File "/usr/local/lib/python2.7/site-packages/picoscope/ps2000a.py", line 62, in <module>
    from picoscope.picobase import _PicoscopeBase
  File "/usr/local/lib/python2.7/site-packages/picoscope/picobase.py", line 49, in <module>
    class _PicoscopeBase(object):
  File "/usr/local/lib/python2.7/site-packages/picoscope/picobase.py", line 978, in _PicoscopeBase
    [0x11F , "PICO_NOT_SUPPORTED_BY_THIS_DEVICE", "A function has been called that is not supported by the current device variant."],
TypeError: list indices must be integers, not tuple
```

I also tried `import picoscope.ps2000a as ps2000a` but it does not work either.

Can you please fix this ?

**Comment by sebma** [comment]
Found why : The 0.6.1 was release before this commit  [fd85268](https://github.com/colinoflynn/pico-python/commit/fd85268ed97f5723ed2d583a8f600ba8598982f5) 

Can you please create a new release tag : 0.6.2 that includes this commit and update : 

`__version__` to 06.2 in `picoscope/__init__.py` ?

**Comment by hmaarrfk** [comment]
Thanks for noticing.

**Comment by sebma** [comment]
@hmaarrfk Great. However, you forgot to update `__version__` in the `picoscope/__init__.py` file.

**Comment by hmaarrfk** [comment]
OK I think i fixed it. You are using a library that only has 2 maintainers. We get busy.

One way to make it easier for you to get the updates you want is to create `pull requests` for these small changes. It makes it easier for me to just "accept" them.
